apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: mydb
    user: user
    password: user_password
    jsonData:
      httpMode: GET
  - name: mysql
    type: mysql
    access: proxy
    url: mysql:3306
    database: logs
    user: user
    password: password
    basicAuth: true
    isDefault: true
    jsonData:
      timezone: "browser"
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: "14400s"
